modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "GNU GPLv3"

[[mods]]
modId = "langsplit"
version = "${version}"
displayName = "Language Splitter"
authors = "fabbe50"
description = '''
To put this simply, I made this mod for my siblings to be able to learn English while playing Minecraft.
It makes it possible to display 2 languages at the same time in the game.
'''
#logoFile = ""

[[dependencies.langsplit]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.langsplit]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.langsplit]]
modId = "architectury"
mandatory = true
versionRange = "[4.5.76,)"
ordering = "AFTER"
side = "BOTH"